[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
# remappings = ["@openzeppelin/=lib/openzeppelin-contracts/"]
# Compiler settings
solc = "0.8.10"
optimizer = true
optimizer_runs = 999
# Testing settings
fuzz = { runs = 1000 }
gas_reports = ["*"]

[profile.ci]
fuzz = { runs = 10_000 }
verbosity = 4

[etherscan]
# mainnet = { key = "${ETHERSCAN_API_KEY}" }
# goerli = { key = "${ETHERSCAN_API_KEY}" }
# sepolia = { key = "${ETHERSCAN_API_KEY}" }
146 = { key = "${SONIC_API_KEY}", url = "${SONIC_API_URL}" }  # Added both key and URL

[rpc_endpoints]
# mainnet = "${MAINNET_RPC_URL}"
# goerli = "${GOERLI_RPC_URL}"
# sepolia = "${SEPOLIA_RPC_URL}"
146 = "${SONIC_RPC_URL}"

